### ISSUE TITLE
Check of system setup exercise

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/ml-cfd-lecture#17]
Hi @JanisGeise,
please have a look at the updated *system_setup.ipynb* notebook.

- [x] commands work as expected
- [x] instructions are clear
- [x] typos/grammar

If anything comes up, please reply to this issue. Otherwise feel free to close this issue
Thanks!

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,
here some feedback regarding the notebook:

problems:
- in case multiple versions of python an are installed, it is necessary to specify the version for the virtual environment. In this case, `python3.8 -m venv ml-cfd` instead of `python -m venv ml-cfd` (also when checking if all the requirements where installed  correctly, use `python3.8` instead of `python`)

suggestions:
- in the section about git, maybe mention that the lecture repository needs to be installed somewhere in `/home/...` as discussed in issue #15 
- before installing ParaView, maybe mention that the virtual environment needs to be deactivated

typos:
- an _l_  is missing the header _Install ParaView_
- maybe replace the _>=_ in the first sentence in the  _Install Python_ section with $\ge$

Everything else worked fine. 

Regards, Janis

**Comment by AndreWeiner** [comment]
Excellent feedback Janis, thanks a lot!
