### ISSUE TITLE
Current ParaView version not compatible with FOAMDataloader

### ISSUE THREAD

**Issue by JanisGeise** [AndreWeiner/ml-cfd-lecture#20]
Hi @AndreWeiner,

just a heads up for the upcoming exercises:

The version of ParaView (v5.7) installed in [exercise 1](https://github.com/AndreWeiner/ml-cfd-lecture/blob/main/notebooks/system_setup.ipynb) uses python 3.7, but the virtual environment is for python3.8. When importing the _flowtorch FOAMDataloader_, this will give the following error:

`Traceback (most recent call last): `
` File "/home/.../dataloader.py", line 7, in <module>`
 ` from flowtorch.data import FOAMDataloader`
 ` File "/home/janis/.local/lib/python3.8/site-packages/flowtorch/data/__init__.py"`
 ` from .tecplot_dataloader import TecplotDataloader`
 `File "/home/janis/.local/lib/python3.8/site-packages/flowtorch/data/tecplot_dataloader.py", line 10, in <module>`
 ` from paraview import servermanager as sm`
`ModuleNotFoundError: No module named 'paraview'`

The issue can be resolved by installing ParaView version _v.5.11_ as described in the [flowtorch repo](https://github.com/FlowModelingControl/flowtorch). When executing python scripts inside an IDE, the paths added to the `~\.bashrc` need to be set in the script before importing _flowtorch_, e.g. as:

`import sys`
`sys.path.insert(0, "/opt/ParaView-5.9.1-MPI-Linux-Python3.8-64bit/bin")`
`sys.path.insert(0, "/opt/ParaView-5.9.1-MPI-Linux-Python3.8-64bit/lib/python3.8/site-packages")`
`from flowtorch.data import FOAMDataloader`

Regards, Janis

**Comment by AndreWeiner** [comment]
Hi Janis,
thanks for the heads-up. I already fixed this issue on the flowTorch side by making the import conditional ([commit](https://github.com/FlowModelingControl/flowtorch/commit/753affc729141fa34857ce0fd9c43f88bc689641)). However, in the requirements.txt, the last flowTorch version from the main branch is installed, where the fix is not yet included. My preferred solution would be to re-install flowTorch in the virtual environment rather than updating ParaView. I'll add a note to both the next exercise and lecture notebooks.
Thanks again!
Andre
