### ISSUE TITLE
Excercise #2+3: source setup-env is not working

### ISSUE THREAD

**Issue by wonskc** [AndreWeiner/ml-cfd-lecture#21]
Hello, I have a question on [Exercise2&3](https://github.com/AndreWeiner/ml-cfd-lecture/blob/main/notebooks/cfd_intro_exercise.ipynb).

I am using Linux run on Virtualbox. The prerequisite to follow Exercise2&3 was well done as explained in Exercise1. 

However, when I run `source setup-env`, I receive the message saying `bash: setup-env: No such file or directory`. 

And I am guessing because of this, when I run `./Allrun`, it is also not working with this message `./Allrun: 3: WM_PROJECT_DIR: parameter not set or null`.

I can't find where I missed it to implement this code well. 

Could you give some advice on this issue?
Thank you in advance,
Wonseok

**Comment by JanisGeise** [comment]
Hi @wonskc, 

unfortunately, I can't reproduce the error (using Virtualbox, version 6.1). Have you executed the command from the top-level of the repository (`ml-cfd-lecture/`)?

If that is the case, what happens if you execute the commands written in the `setup-env` manually (just copy each line in the file into the terminal; also from the top-level of the repository) and then try executing the `./Allrun` script.


Regards, Janis

**Comment by wonskc** [comment]
@JanisGeise,

thank you a lot. I found that I don't have a file `setup-env` itself in the repository and figured out that I missed to do `git pull` before. 

Best,
Wonseok

**Comment by AndreWeiner** [comment]
Thanks to the two of you for bringing up and solving this issue. I'll add a note to today's lecture to pull the material frequently.
Best, Andre
