### ISSUE TITLE
Check/test of exercise 3/4 part I

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/ml-cfd-lecture#23]
Hi @JanisGeise,

I pushed a revised version of exercise 3 (next week's exercise). I didn't have time to test the instructions thoroughly. Please let me know if further revision is needed. The revision of the second part and the lecture notebook will have to wait until Monday.

Thanks!
Andre

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,

the first part of the exercise works without any problems. In my opinion, all instructions are clear and understandable.

Regards
Janis

**Comment by AndreWeiner** [comment]
Great, thanks for testing! I update this issue once there are updates on the lecture/exercise.
Best, Andre

**Comment by AndreWeiner** [comment]
Hi @JanisGeise,
a small update: the revised lecture notebook is now online. The explanations towards the end of the notebook are sparse due to time constraints. If there is something really essential to write some more lines about, please let me know.
Thanks!
Andre

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,

in my opinion (if it's possible in the remaining time) it would be helpful to add one or two more sentences when explaining overfitting (prior section "Training with batches of data").

Regards, 
Janis

**Comment by AndreWeiner** [comment]
Hi @JanisGeise,
I completed and pushed exercise 5, the second part of the ML intro exercise. I'll upload a quick&dirty solution to your cloud storage in case you get stuck.
Best, Andre

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,

I finished exercise 5, everything worked fine. I have one suggestion though:

In my opinion, it would be helpful to add a note to the "Direct learning approach" part (as tip / advice) to start with a rather "simple" model for the baseline model, because it may be confusing which of the presented models is best to use as a baseline model since the lecture notebook covers a wide range of methods up to quite complex techniques.

Unrelated to that, I added a function for the hyperparameter tuning to your solution script and uploaded it into the cloud, in case you need it.

Regards,
Janis

**Comment by AndreWeiner** [comment]
Hi @JanisGeise,
thanks for the script - I'll show the function to perform the parameter study if requested and time allows. I included a note to start with a simple network and a simple training routine for the baseline model.
Best, Andre
