### ISSUE TITLE
 amd64 vs arm64 architecture

### ISSUE THREAD

**Issue by Devendra0801** [AndreWeiner/ml-cfd-lecture#28]
Hello,

Did anyone faced the problem of CPU architecture while setting up the platform for exercises on Linux (Especially on MacOS). I did all the installation as per given instructions. However when I ran the sample program of (lolcow) I got the following error. 

"FATAL:   could not open image /home/dev/Desktop/lolcow_latest.sif: the image's architecture (amd64) could not run on the host's (arm64)"

Is there anyone who has faced the same issue and know how one can run amd64 on arm64 architecture.

Thanks.

**Comment by AndreWeiner** [comment]
Hi @Devendra0801,

I am afraid it will be tricky for you to make the lecture material work on arm64. The lecture container is built for amd64 architecture so it won't work either, and it is not straightforward to re-build the container for another architecture, since it relies on pre-compiled libraries. Your best chance to make the material work is a native installation/compilation of all required packages. The following links may guide you:

- for OpenFOAM and ParaView have a look at [this link](https://develop.openfoam.com/Development/openfoam/-/blob/master/doc/Build.md)
- for PyTorch and LibTorch, you can try the [official binaries](https://pytorch.org/get-started/locally/) for MAC

Unfortunately, I can't test any instructions since I don't have access to a MAC.

Best, Andre

**Comment by Devendra0801** [comment]
> Hi @Devendra0801,
> 
> I am afraid it will be tricky for you to make the lecture material work on arm64. The lecture container is built for amd64 architecture so it won't work either, and it is not straightforward to re-build the container for another architecture, since it relies on pre-compiled libraries. Your best chance to make the material work is a native installation/compilation of all required packages. The following links may guide you:
> 
> * for OpenFOAM and ParaView have a look at [this link](https://develop.openfoam.com/Development/openfoam/-/blob/master/doc/Build.md)
> * for PyTorch and LibTorch, you can try the [official binaries](https://pytorch.org/get-started/locally/) for MAC
> 
> Unfortunately, I can't test any instructions since I don't have access to a MAC.
> 
> Best, Andre

Dear Prof. Weiner,

Thank you for your reply. I tried making changes from those links and many other sources but could not solve the problem. Finally I have decided to install linux in my old windows laptop.

Regards
Devendra

**Comment by AndreWeiner** [comment]
Alright, thanks for the feedback. I hope to compile some instructions for MAC in the future.
Best, Andre
