### ISSUE TITLE
Open/closed-loop exercises

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/ml-cfd-lecture#30]
Hi @JanisGeise,
I completed the revision of the control exercises. Please let me know if further modifications or clarifications are needed.
Thanks!
Andre

**Comment by JanisGeise** [comment]
Hi @AndreWeiner,

I have two minor suggestions / issues. As far as I know,  for the final result of the controlled flow `purgeWrite`  in the `controlDict` needs to be set to `0` when using the *base* case,  because otherwise the time folders are overwritten with the latest time step. Further, decreasing the `writeInterval` in the `controlDict` to e.g. `0.01` may be helpful to animate the flow field nicely, because in the default setup of the base case only every second is written. 

Lastly, in the default setup of *drlfoam* there are currently 12 probes placed in the wake (probably just a typo).

Regards,
Janis

**Comment by AndreWeiner** [comment]
Hi @JanisGeise,
both remarks are absolutely correct, thanks!
Andre
